x-config: &base-config
  TZ: Europe/Moscow
  telegram_token: "12345:abcd"
  telegram_admins: '["267519921", "1234567", "666555444"]'
  mongo_dsn: mongodb://mongo:27017
  redis_dsn: redis://redis:6379

services:
  craftbot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: "craftbot"
    environment:
      <<: *base-config

  craftbot.API:
    build:
      context: .
      dockerfile: Dockerfile.API
    restart: always
    container_name: "craftbot.API"
    environment:
      <<: *base-config

  mongo:
    image: mongo:4.4.18  # последняя версия без AVX инструкций
    container_name: craftbot-mongo
    restart: always
    volumes:
      - mongodb:/data/db
      - mongodb:/data/configdb

  redis:
    image: redis:latest
    container_name: craftbot-redis
    restart: always
    volumes:
        - redis:/data

volumes:
  mongo:
  redis:
