[tool.black]
line-length = 99
target-version = ['py39']
exclude = '''
(
    \.git
  | venv
  | \.vscode
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 99